"use client"
import { Outfit, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { Toaster } from "@/components/ui/sonner"
import { usePathname } from "next/navigation";
import { useState } from "react";
import { CartContext } from "./_context/cartContext";
const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  //!hide header in sign in  page
  const params = usePathname()
  const [updateCart,setUpdateCart]=useState(false)
  const showHeader = params=="/sign-in" || params=="/create-account" ? false : true
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${geistMono.variable} antialiased`}
      >
        <CartContext.Provider value={{updateCart,setUpdateCart}}>
        {showHeader && <Header />}
        {children}
        <Toaster />
        </CartContext.Provider>
      </body>
    </html>
  );
}
